# Generated by Django 3.0.2 on 2020-03-02 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OraclePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postQuestion', models.TextField(max_length=500)),
                ('postAnswer', models.TextField(max_length=500, null=True)),
                ('postTime', models.DateTimeField(auto_now_add=True)),
                ('isAnswered', models.BooleanField(default=False)),
                ('postAnswerer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answeredBy', to=settings.AUTH_USER_MODEL)),
                ('postUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
