# Generated by Django 3.0.2 on 2020-02-16 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200215_0002'),
        ('oracle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oraclepost',
            old_name='postAnswered',
            new_name='isAnswered',
        ),
        migrations.AddField(
            model_name='oraclepost',
            name='postAnswer',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='oraclepost',
            name='postUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
