# Generated by Django 3.0.2 on 2020-02-17 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oracle', '0002_auto_20200216_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oraclepost',
            name='postUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
