# Generated by Django 3.0.2 on 2020-03-02 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestName', models.CharField(max_length=20, unique=True)),
                ('contestDate', models.DateField()),
                ('contestHours', models.PositiveSmallIntegerField(default=2)),
                ('contestMinutes', models.PositiveSmallIntegerField(default=0)),
                ('contestDuration', models.DurationField(default=datetime.timedelta(days=-1, seconds=7200))),
                ('isRunning', models.BooleanField(default=False)),
            ],
        ),
    ]
