# Generated by Django 3.0.2 on 2020-02-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contestDate',
            field=models.DateField(),
        ),
    ]
