# Generated by Django 3.0.2 on 2020-02-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contestants',
            field=models.ManyToManyField(blank=True, to='users.User'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contestDate',
            field=models.DateField(),
        ),
    ]
