# Generated by Django 3.0.2 on 2020-03-02 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contest_contestants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contestDuration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
    ]
