# Generated by Django 3.0.2 on 2020-02-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200214_2324'),
        ('contests', '0002_auto_20200214_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contestants',
            field=models.ManyToManyField(blank=True, null=True, to='users.User'),
        ),
    ]
