# Generated by Django 3.0.2 on 2020-02-04 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('contests', '0002_auto_20200203_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contestants',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
