# Generated by Django 3.0.2 on 2020-02-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200214_2330'),
        ('contests', '0003_auto_20200214_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contestants',
            field=models.ManyToManyField(blank=True, to='users.User'),
        ),
    ]
