# Generated by Django 3.0.2 on 2020-02-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contest_contestants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contestants',
        ),
    ]
