# Generated by Django 3.0.2 on 2020-02-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('contests', '0004_remove_contest_contestants'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contestants',
            field=models.ManyToManyField(to='users.User'),
        ),
    ]
