# Generated by Django 3.0.2 on 2020-03-02 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_contestproblems'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionName', models.CharField(max_length=1000, unique=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestproblems', to='contests.Contest')),
            ],
        ),
        migrations.DeleteModel(
            name='ContestProblems',
        ),
    ]
