# Generated by Django 3.0.2 on 2020-03-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20200302_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestproblem',
            name='contest',
        ),
        migrations.AddField(
            model_name='contest',
            name='contestQuestions',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.ContestProblem'),
        ),
    ]
