# Generated by Django 3.0.2 on 2020-02-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_participatingin'),
        ('contests', '0005_contest_contestants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contestants',
            field=models.ManyToManyField(blank=True, to='users.User'),
        ),
    ]
