# Generated by Django 3.0.2 on 2020-03-02 17:45

from django.db import migrations


class Migration(migrations.Migration):
   
    dependencies = [
        ('contests', '0006_auto_20200302_1041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContestProblem',
            new_name='Problem',
        ),
    ]
