# Generated by Django 3.0.2 on 2020-02-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_participatingin'),
        ('contests', '0006_auto_20200204_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contestants',
            field=models.ManyToManyField(blank=True, null=True, to='users.User'),
        ),
    ]
