# Generated by Django 3.0.2 on 2020-02-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200204_0105'),
        ('contests', '0007_auto_20200204_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contestants',
            field=models.ManyToManyField(blank=True, to='users.User'),
        ),
    ]
