# Generated by Django 3.0.2 on 2020-03-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20200302_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='questionName',
        ),
        migrations.AddField(
            model_name='problem',
            name='problemInformation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='problemName',
            field=models.CharField(default='Another Problem', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='problemTests',
            field=models.TextField(null=True),
        ),
    ]
