# Generated by Django 3.0.2 on 2020-03-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_auto_20200302_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='contestQuestions',
            new_name='contestProblems',
        ),
    ]
