# Generated by Django 3.0.2 on 2020-03-02 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_auto_20200302_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contestProblems',
        ),
        migrations.AddField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contestproblems', to='contests.Contest'),
        ),
    ]
