# Generated by Django 3.0.2 on 2020-03-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_contest_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='stopTime',
            field=models.TimeField(null=True),
        ),
    ]
