# Generated by Django 3.0.2 on 2020-04-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0013_auto_20200416_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='isPaused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='pauseTime',
            field=models.TimeField(null=True),
        ),
    ]
