# Generated by Django 3.0.2 on 2020-02-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('userType', models.CharField(choices=[('administrator', 'ADMINISTRATOR'), ('participant', 'PARTICIPANT'), ('grader', 'GRADER')], default='participant', max_length=20)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
