# Generated by Django 3.0.2 on 2020-03-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('userName', models.CharField(max_length=30, unique=True)),
                ('userType', models.CharField(choices=[('administrator', 'ADMINISTRATOR'), ('team', 'Team'), ('grader', 'GRADER')], default=('team', 'Team'), max_length=20)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('admin', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('participatingIn', models.ManyToManyField(blank=True, to='contests.Contest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
