# Generated by Django 3.0.2 on 2020-02-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_contest_contestants'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='participatingIn',
            field=models.ManyToManyField(blank=True, to='contests.Contest'),
        ),
    ]
