# Generated by Django 3.0.2 on 2020-04-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userNameDetail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
