# Generated by Django 3.0.2 on 2020-02-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20200204_0104'),
        ('users', '0002_user_participatingin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='participatingIn',
            field=models.ManyToManyField(blank=True, null=True, to='contests.Contest'),
        ),
    ]
