# Generated by Django 3.0.2 on 2020-02-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_auto_20200204_0107'),
        ('users', '0003_auto_20200204_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='participatingIn',
            field=models.ManyToManyField(blank=True, to='contests.Contest'),
        ),
    ]
