# Generated by Django 3.0.2 on 2020-02-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20200214_2330'),
        ('users', '0004_auto_20200214_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='participatingIn',
            field=models.ManyToManyField(blank=True, null=True, to='contests.Contest'),
        ),
    ]
