# Generated by Django 3.0.2 on 2020-02-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20200215_0002'),
        ('users', '0005_auto_20200214_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='participatingIn',
            field=models.ManyToManyField(blank=True, to='contests.Contest'),
        ),
    ]
