# Generated by Django 3.0.2 on 2020-03-16 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import submission.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0010_auto_20200302_1225'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionFile', models.FileField(blank=True, null=True, upload_to=submission.models.get_upload_path)),
                ('submissionName', models.CharField(max_length=25, null=True)),
                ('submissionTime', models.DateTimeField(auto_now_add=True)),
                ('submissionProblem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associatedProblem', to='contests.Problem')),
                ('submissionTeam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitteBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
