# Generated by Django 3.0.2 on 2020-03-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20200316_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submissionGrade',
            field=models.BooleanField(default=False),
        ),
    ]
