# Generated by Django 3.0.2 on 2020-03-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_submission_submissiongrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submissionGrade',
            field=models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL'), ('ungraded', 'ungraded')], default=('ungraded', 'ungraded'), max_length=8),
        ),
    ]
