# Generated by Django 3.0.2 on 2020-03-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20200317_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submissionGrade',
            field=models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL'), ('ungraded', 'UNGRADED'), ('inprocess', 'INPROCESS')], default='ungraded', max_length=9),
        ),
    ]
