# Generated by Django 3.0.2 on 2020-03-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_submission_totalsubmissioncount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='totalSubmissionCount',
            field=models.FloatField(default=0.0),
        ),
    ]
