# Generated by Django 3.0.2 on 2020-03-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_auto_20200320_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submissionTime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
