# Generated by Django 3.0.2 on 2020-03-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_auto_20200322_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='totalSubmissionCount',
            field=models.IntegerField(default=0),
        ),
    ]
