# Generated by Django 3.0.2 on 2020-04-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0010_auto_20200322_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submissionLanguage',
            field=models.CharField(choices=[('java', 'JAVA'), ('c++', 'C++'), ('c', 'C'), ('python', 'PYTHON'), ('c#', 'C#')], default='c', max_length=6),
        ),
    ]
