# Generated by Django 3.0.2 on 2020-04-17 00:29

from django.db import migrations, models
import submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_submission_submissionlanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submissionFile',
            field=models.FileField(upload_to=submission.models.get_upload_path),
        ),
    ]
