# Generated by Django 3.0.2 on 2020-04-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_auto_20200416_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='subTouchTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
