# Generated by Django 3.0.2 on 2020-04-24 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('submission', '0013_submission_subtouchtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='subTouchTime',
            new_name='subTouchTime',
        ),
    ]
