# Generated by Django 3.0.2 on 2020-05-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0015_auto_20200424_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submissionLanguage',
            field=models.CharField(choices=[('java', 'JAVA'), ('c++', 'C++'), ('c', 'C'), ('python', 'PYTHON')], default='c', max_length=6),
        ),
    ]
